### ISSUE TITLE
About source code and dataset

### ISSUE THREAD

**Issue by kuraga** [sismetanin/rureviews#1]
@sismetanin , am I right that pre-trained word embedding are published here, _**only**_?

Thanks!

**Comment by sismetanin** [comment]
Hey @kuraga,
In addition to pre-trained embeddings, the sentiment dataset is also published in this repo.

**Comment by kuraga** [comment]
Yes, https://github.com/sismetanin/rureviews/blob/master/women-clothing-accessories.3-class.balanced.csv. Sorry.
